### PR TITLE
fix issues with zero one

### LINKED ISSUE #60: iszero
Not high priority but this won't work if the `SparseCoefficients` is not canonicalized:

https://github.com/JuliaAlgebra/StarAlgebras.jl/blob/ba3697f45b957b1881950aa096932a42b1cc7c9b/src/coefficients.jl#L37

This doesn't work for tuples:

https://github.com/JuliaAlgebra/StarAlgebras.jl/blob/ba3697f45b957b1881950aa096932a42b1cc7c9b/src/types.jl#L92

### LINKED ISSUE #80: `one` with FixedBasis (and probably `isone`) are broken
And the latter probably even more than the former :P
```julia
julia> import StarAlgebras as SA;

julia> SA.star(s::String) = reverse(s) # identity is also fine

julia> b = SA.FixedBasis(["", "a", "b", "aa", "ab", "ba", "bb"]);

julia> A = SA.StarAlgebra(String, SA.DiracMStructure(b, *))
*-algebra of String

julia> one(A)
ERROR: MethodError: no method matching iterate(::Type{String})
The function `iterate` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  iterate(::JuliaInterpreter.ExprSplitter)
   @ JuliaInterpreter ~/.julia/packages/JuliaInterpreter/O4pqe/src/construct.jl:545
  iterate(::JuliaInterpreter.ExprSplitter, ::Any)
   @ JuliaInterpreter ~/.julia/packages/JuliaInterpreter/O4pqe/src/construct.jl:545
  iterate(::LazyString)
   @ Base strings/lazy.jl:94
  ...

Stacktrace:
 [1] isempty(itr::Type)
   @ Base ./essentials.jl:1121
 [2] StarAlgebras.DiracBasis(itr::Type)
   @ StarAlgebras ~/.julia/dev/StarAlgebras/src/bases_dirac.jl:29
 [3] one(T::Type, A::StarAlgebras.StarAlgebra{DataType, String, StarAlgebras.DiracMStructure{String, Int64, StarAlgebras.FixedBasis{String, Int64, Vector{String}}, typeof(*)}})
   @ StarAlgebras ~/.julia/dev/StarAlgebras/src/types.jl:94
 [4] one(A::StarAlgebras.StarAlgebra{DataType, String, StarAlgebras.DiracMStructure{String, Int64, StarAlgebras.FixedBasis{String, Int64, Vector{String}}, typeof(*)}})
   @ StarAlgebras ~/.julia/dev/StarAlgebras/src/types.jl:85
 [5] top-level scope
   @ REPL[75]:1
```

even with non-empty object: 
```julia
julia> A = SA.StarAlgebra("ab", SA.DiracMStructure(b, *))

julia> one(A)
ERROR: MethodError: no method matching getindex(::StarAlgebras.DiracBasis{Char, String}, ::String)
The function `getindex` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  getindex(::StarAlgebras.DiracBasis{T}, ::T) where T
   @ StarAlgebras ~/.julia/dev/StarAlgebras/src/bases_dirac.jl:56

Stacktrace:
 [1] coeffs!
   @ ~/.julia/dev/StarAlgebras/src/bases.jl:79 [inlined]
 [2] coeffs(cfs::StarAlgebras.SparseCoefficients{String, Int64, Vector{String}, Vector{Int64}}, source::StarAlgebras.DiracBasis{Char, String}, target::StarAlgebras.FixedBasis{String, Int64, Vector{String}})
   @ StarAlgebras ~/.julia/dev/StarAlgebras/src/bases.jl:73
 [3] one(T::Type, A::StarAlgebras.StarAlgebra{String, String, StarAlgebras.DiracMStructure{String, Int64, StarAlgebras.FixedBasis{String, Int64, Vector{String}}, typeof(*)}})
   @ StarAlgebras ~/.julia/dev/StarAlgebras/src/types.jl:94
 [4] one(A::StarAlgebras.StarAlgebra{String, String, StarAlgebras.DiracMStructure{String, Int64, StarAlgebras.FixedBasis{String, Int64, Vector{String}}, typeof(*)}})
   @ StarAlgebras ~/.julia/dev/StarAlgebras/src/types.jl:85
 [5] top-level scope
   @ REPL[77]:1

```
We assume more from the object than what we write?

### PR DESCRIPTION
**Pull request by kalmarek**
there's one commented out branch in `__coerce` that would require us to handle one more example, but this requires that `object(A)` is iterable, which might be too much? I'm not sure if the case covered by it is worth the trouble.

closes #80
closes #60

### CODE REVIEW

File: src/types.jl [hunk 1]
```diff
@@ -76,55 +76,51 @@ function AlgebraElement(
...
+    if id in basis(A)
+        for (i, v) in nonzero_pairs(coeffs(a))
+            isone(v) || return false
+            id == basis(A)[i] || return false
+        end
+        return true
     else
-        dc = coeffs(c, basis(a), DiracBasis(object(parent(a))))
-        return dc == cfs1
+        return a == one(a)
```
Comment (blegat) [inline src/types.jl:118]: I don't understand this case. If `basis(A)` does not contain one then we can't accept any terms so we can just do `return iszero(a)`, no ?

**Review by blegat — DISMISSED** [review]

File: src/types.jl (hunk 1 above)
Comment (kalmarek) [reply src/types.jl:118]: why should we return `iszero(a)` from the function in question (`isone(a)`) ? 😀

Comment (blegat) [reply src/types.jl:118]: I was thinking that if 1 is not in the span of the basis then we should just do `return false`. My internal brain LLM hallucinated `iszero(a)` instead of `false`.

**Comment by kalmarek** [comment]
@blegat what do you think about those failures on julia-pre? 
The only change is `@test` to `@test_throws`

File: src/types.jl [hunk 2]
```diff
@@ -33,13 +33,16 @@ function MA.promote_operation(::typeof(basis), ::Type{StarAlgebra{O,T,M}}) where
     return MA.promote_operation(basis, M)
 end
 object(A::StarAlgebra) = A.object
+Base.isempty(A::StarAlgebra) = isempty(object(A))
```
Comment (blegat) [inline src/types.jl:36]: I would rather call `isempty` to the basis. `object(A)` is responsible to generating `one(A)` but we agreed that it is not necessarily the same as the iterator in the basis.

**Comment by kalmarek** [comment]
oh, interesting, now it's a different error, previously it was a plain segfault? hmm...

the types in the backtrace are unwieldy...

**Comment by kalmarek** [comment]
ok, now there;s another segfault on macos; I can't reproduce it locally; @blegat merging?

**Review by blegat — APPROVED** [review]
Yes, let's hope it disappears when they release
